#!/bin/bash
#PBS -N rra_pack_np2
#PBS -q short_cpuQ
#PBS -l select=1:ncpus=2:mem=4gb
#PBS -l place=pack
#PBS -l walltime=00:20:00
#PBS -o rra_pack_np2.o
#PBS -e rra_pack_np2.e

cd $PBS_O_WORKDIR

for MODULE in "mpich-3.2 cmake-3.10.2 gcc91"; do
  module load ""
done

export MEASURE_SPEEDUP=1
export PRRO_SEED=42
export PRRO_PLACEMENT=pack

mpirun.actual -n 2 \
    ./parallel/bin/rra_parallel \
    ./datasets/random-128-100.csv \
    -600 600 \
    1000 \
    50 \
    10 \
    1.0 \
    ./output
